### ISSUE TITLE
serdashop also made a cs9236 waveblaster card

### ISSUE THREAD

**Issue by nikitalita** [ivop/cs9236-waveblaster#1]
https://www.serdashop.com/CrystalBlaster-C2

**Comment by ivop** [comment]
Yes, I know. It's my design. He first created the CrystalBlaster C1 Ivo Edition, which was a DIY THT kit with a reduced footprint compared to my original design. Now, he has further reduced the footprint, and it's called CrystalBlaster C2.

Have fun!
Ivo
